
name: 'jaffle_shop'
version: '0.1'
config-version: 2
profile: 'jaffle_shop'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"
    - "logs"

models:
  jaffle_shop:
      materialized: table
      staging:
        materialized: view
        tags: ["staging", "hourly"]

# comment 2